export const metadata = {
  title: 'Pedro Carvalho Personal Webiste',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
