import '../globals.css'
import Layout from "./components/Layout";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: 'My Personal Site',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="en">
      <head/>
      <body className="max-w-3xl mx-auto py-10">
        <Navbar/>
          <Layout>
            {children}
          </Layout>
          <Footer/>
      </body>
    </html>
  )
};