import '../globals.css'
import Link from 'next/link'
import { getPages } from '@/sanity/sanity-utils'

export const metadata = {
  title: 'Pedro Carvalho Personal Webiste',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout ({ children }: { children: React.ReactNode }) {

  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className='max-w-5xl mx-auto px-5 py-10'>
        <header className='flex items-center justify-between'>
          <Link 
            href="/"
            className="bg-gradient-to-r from-blue-300 via-blue-500 to-blue-700
            bg-clip-text text-transparent text-lg font-bold"
          >
            Pedro 
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='hover:underline'>
                {page.title} 
              </Link>
            ))}
          </div>
        </header>
          <main className="py-20">{children}</main>
        <footer className="text-right" >&copy; 2023 Pedro Carvalho. All rights reserved.</footer>
      </body>
    </html>
  )
}